os: osx
osx_image: xcode9.4
language: generic
node_js:
- 0.8
jdk:
- oraclejdk8

- npm install -g eslint
- npm install -g jasmine-core
- npm install -g karma
- npm install -g karma-coverage
- npm install -g karma-jasmine
- npm install -g karma-jasmine-jquery
- npm install -g karma-phantomjs-launcher