dist:            trusty
language: node_js
node_js:
- 10
before_script:
- if [[ "$TRAVIS_COMMIT_MESSAGE" == *"lightning"* ]] || [[ "$TRAVIS_COMMIT_MESSAGE" == *"classic"* ]]; then
      npm install -g eslint;
  fi
# - npm install -g eslint
# - npm install -g jasmine-core
# - npm install -g karma
# - npm install -g karma-coverage
# - npm install -g karma-jasmine
# - npm install -g karma-jasmine-jquery
# - npm install -g karma-phantomjs-launcher
jobs:
  include:
    - stage: "UnitTests"               
      name: "Unit Tests"           
      script: 
      - npm install -g eslint
      - npm install -g jasmine-core
    - stage: "LexAutomation"               
      name: "Lightning Test Automation"           
      script: 
      - npm install -g karma
      - npm install -g karma-jasmine
    - stage: "ClassicAutomation"
      name: "Classic Test Automation"
      script:
      - npm install -g karma-jasmine-jquery
      -  npm install -g karma-phantomjs-launcher
script:
- node -v
