dist:            trusty
language: node_js
node_js:
- 10
before_script:
- if [[ ("$TRAVIS_PULL_REQUEST" = "false") && ("$TRAVIS_BRANCH" = "master") ]]; then
      npm install -g eslint;
  fi
- if [[ "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_COMMIT_MESSAGE" == *"lightning"* || *"install-biz-policy"*  ]]; then
      npm install -g eslint;
  fi
# - npm install -g eslint
# - npm install -g jasmine-core
# - npm install -g karma
# - npm install -g karma-coverage
# - npm install -g karma-jasmine
# - npm install -g karma-jasmine-jquery
# - npm install -g karma-phantomjs-launcher
script:
- node -v
