dist:            trusty
language: node_js
node_js:
- 10
before_script:
- if [[ "$TRAVIS_COMMIT_MESSAGE" == *"lightning"* ]] || [[ "$TRAVIS_COMMIT_MESSAGE" == *"classic"* ]]; then
      npm install -g eslint;
  fi
# - npm install -g eslint
# - npm install -g jasmine-core
# - npm install -g karma
# - npm install -g karma-coverage
# - npm install -g karma-jasmine
# - npm install -g karma-jasmine-jquery
# - npm install -g karma-phantomjs-launcher
jobs:
  include:
    - stage: "Unit-tests"               
      name: "Unit Tests"           
      before_script: 
      - if [[ "$TRAVIS_EVENT_TYPE" != "cron"  ]]; then
          travis_terminate 0;
        fi
      - npm install -g eslint
      - npm install -g jasmine-core
#     - stage: "Lightning-functionality-test-automation"               
#       name: "Lightning Test Automation"           
#       before_script: 
#       - npm install -g karma
#       - npm install -g karma-jasmine
#     - stage: "Classic-functionality-test-automation"
#       name: "Classic Test Automation"
#       before_script:
#       - npm install -g karma-jasmine-jquery
#       - npm install -g karma-phantomjs-launcher
script:
- node -v
