os: osx
osx_image: xcode9.4
language: node_js
node_js:
- 0.8
jdk:
- oraclejdk8
before_script:
- sudo npm install -g eslint
- sudo npm install -g jasmine-core
- sudo npm install -g karma
- sudo npm install -g karma-coverage
- sudo npm install -g karma-jasmine
- sudo npm install -g karma-jasmine-jquery
- sudo npm install -g karma-phantomjs-launcher